In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [21]:
import numpy as np

# Given flat data
haha = "4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 1 0 0 1 1 0 0 1 1 0 0 1 1 2 2 1 1 0 0 1 1 0 0 1 1 0 0 1 1 2 2 1 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4"
flat = list(map(float, haha.split()))

# Dimensions
mx, my, mz = 4, 4, 4

# Reshape to 3D
arr3d = np.array(flat).reshape((mz, my, mx))

# Extract and print each face
print("Back face (k=0):")
print(arr3d[0, :, :], "\n")

print("Front face (k=3):")
print(arr3d[3, :, :], "\n")

print("Bottom face (j=0):")
print(arr3d[:, 0, :], "\n")

print("Top face (j=3):")
print(arr3d[:, 3, :], "\n")

print("Left face (i=0):")
print(arr3d[:, :, 0], "\n")

print("Right face (i=3):")
print(arr3d[:, :, 3], "\n")


Back face (k=0):
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]] 

Front face (k=3):
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]] 

Bottom face (j=0):
[[4. 4. 4. 4.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [4. 4. 4. 4.]] 

Top face (j=3):
[[4. 4. 4. 4.]
 [1. 2. 2. 1.]
 [1. 2. 2. 1.]
 [4. 4. 4. 4.]] 

Left face (i=0):
[[4. 4. 4. 4.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [4. 4. 4. 4.]] 

Right face (i=3):
[[4. 4. 4. 4.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [4. 4. 4. 4.]] 



In [20]:
arr3d[1, :, :]

array([[1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 2., 2., 1.]])