In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
import numpy as np

# Given flat data
haha = "4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 1 5 5 1 1 5 5 1 1 5 5 1 1 7 7 1 1 5 5 1 1 5 5 1 1 5 5 1 1 7 7 1 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4"
flat = list(map(float, haha.split()))

# Dimensions
mx, my, mz = 4, 4, 4

# Reshape to 3D
arr3d = np.array(flat).reshape((mz, my, mx))

# Extract and print each face
arr3d[0, :, :]


array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [5]:
# 이제 각 면(ghost layer) 확인
print("i=0\n", arr3d[:, :, 0])
print("i=-1\n", arr3d[:, :, -1])

print("j=0\n", arr3d[:, 0, :])
print("j=-1\n", arr3d[:, -1, :])

print("k=0\n", arr3d[0, :, :])
print("k=-1\n", arr3d[-1, :, :])

i=0
 [[4. 4. 4. 4.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [4. 4. 4. 4.]]
i=-1
 [[4. 4. 4. 4.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [4. 4. 4. 4.]]
j=0
 [[4. 4. 4. 4.]
 [1. 5. 5. 1.]
 [1. 5. 5. 1.]
 [4. 4. 4. 4.]]
j=-1
 [[4. 4. 4. 4.]
 [1. 7. 7. 1.]
 [1. 7. 7. 1.]
 [4. 4. 4. 4.]]
k=0
 [[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]
k=-1
 [[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]
