In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
import numpy as np

# Given flat data
haha = "0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0 2 1 1 1 1 1 2"
flat = list(map(float, haha.split()))

# Dimensions
mx, my= 6, 6

# Reshape to 3D
arr3d = np.array(flat).reshape((my, mx))


In [9]:
# 이제 각 면(ghost layer) 확인
print("i=0\n", arr3d[:, 0])
print("i=-1\n", arr3d[:, -1])

print("j=0\n", arr3d[0, :])
print("j=-1\n", arr3d[-1, :])

i=0
 [0. 0. 0. 0. 0. 1.]
i=-1
 [2. 2. 2. 2. 2. 2.]
j=0
 [0. 0. 0. 0. 0. 2.]
j=-1
 [1. 1. 1. 1. 1. 2.]


In [10]:
arr3d

array([[0., 0., 0., 0., 0., 2.],
       [0., 0., 0., 0., 0., 2.],
       [0., 0., 0., 0., 0., 2.],
       [0., 0., 0., 0., 0., 2.],
       [0., 0., 0., 0., 0., 2.],
       [1., 1., 1., 1., 1., 2.]])