In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Debug Domain communicate

In [ ]:
# Given flat data
haha = "0 0 0 0 2 0 0 0 0 2 0 0 0 0 2 0 0 0 0 2 1 1 1 1 1"
flat = list(map(float, haha.split()))

# Dimensions
mx, my= 5, 5

# Reshape to 3D
arr3d = np.array(flat).reshape((my, mx))


In [2]:
# 이제 각 면(ghost layer) 확인
print("i=0\n", arr3d[:, 0])
print("i=-1\n", arr3d[:, -1])

print("j=0\n", arr3d[0, :])
print("j=-1\n", arr3d[-1, :])

i=0
 [0. 0. 0. 0. 1.]
i=-1
 [2. 2. 2. 2. 1.]
j=0
 [0. 0. 0. 0. 2.]
j=-1
 [1. 1. 1. 1. 1.]


In [3]:
arr3d

array([[0., 0., 0., 0., 2.],
       [0., 0., 0., 0., 2.],
       [0., 0., 0., 0., 2.],
       [0., 0., 0., 0., 2.],
       [1., 1., 1., 1., 1.]])

# Debug rhs

In [35]:
nx = 15 # 여기서는 cell의 개수
ny = 15
Lx = 1
Ly = 1
dx = 1/(nx)
dy = 1/ny

f = np.zeros((nx+2, ny+2))

x = np.zeros(nx+2)
y = np.zeros(ny+2)

for i in range(nx+2):
    x[i] = dx/2 + (i-1)*dx
for j in range(ny+2):
    y[j] = dy/2 + (j-1)*dy

for i in range(nx+2):
    for j in range(ny+2):
        f[i][j] = -2 * np.pi * np.sin(np.pi*x[i]) * np.sin(np.pi*y[j])

In [36]:
np.set_printoptions(threshold=np.inf, linewidth=np.inf) 
f

array([[-0.06865134,  0.06865134,  0.20295362,  0.32838585,  0.43946605,  0.53133947,  0.59999081,  0.64241967,  0.6567717 ,  0.64241967,  0.59999081,  0.53133947,  0.43946605,  0.32838585,  0.20295362,  0.06865134, -0.06865134],
       [ 0.06865134, -0.06865134, -0.20295362, -0.32838585, -0.43946605, -0.53133947, -0.59999081, -0.64241967, -0.6567717 , -0.64241967, -0.59999081, -0.53133947, -0.43946605, -0.32838585, -0.20295362, -0.06865134,  0.06865134],
       [ 0.20295362, -0.20295362, -0.59999081, -0.97080552, -1.29919137, -1.57079633, -1.77374994, -1.89918218, -1.94161104, -1.89918218, -1.77374994, -1.57079633, -1.29919137, -0.97080552, -0.59999081, -0.20295362,  0.20295362],
       [ 0.32838585, -0.32838585, -0.97080552, -1.57079633, -2.1021358 , -2.54160185, -2.8699877 , -3.07294132, -3.14159265, -3.07294132, -2.8699877 , -2.54160185, -2.1021358 , -1.57079633, -0.97080552, -0.32838585,  0.32838585],
       [ 0.43946605, -0.43946605, -1.29919137, -2.1021358 , -2.8132068 , -3.4013

In [37]:
haha = "-0.0686513 0.0686513 0.202954 0.328386 0.439466 0.531339 0.599991 0.64242 0.656772 0.64242 0.0686513 -0.0686513 -0.202954 -0.328386 -0.439466 -0.531339 -0.599991 -0.64242 -0.656772 -0.64242 0.202954 -0.202954 -0.599991 -0.970806 -1.29919 -1.5708 -1.77375 -1.89918 -1.94161 -1.89918 0.328386 -0.328386 -0.970806 -1.5708 -2.10214 -2.5416 -2.86999 -3.07294 -3.14159 -3.07294 0.439466 -0.439466 -1.29919 -2.10214 -2.81321 -3.40133 -3.84079 -4.1124 -4.20427 -4.1124 0.531339 -0.531339 -1.5708 -2.5416 -3.40133 -4.1124 -4.64374 -4.97212 -5.0832 -4.97212 0.599991 -0.599991 -1.77375 -2.86999 -3.84079 -4.64374 -5.24373 -5.61454 -5.73998 -5.61454 0.64242 -0.64242 -1.89918 -3.07294 -4.1124 -4.97212 -5.61454 -6.01158 -6.14588 -6.01158 0.656772 -0.656772 -1.94161 -3.14159 -4.20427 -5.0832 -5.73998 -6.14588 -6.28319 -6.14588 0.64242 -0.64242 -1.89918 -3.07294 -4.1124 -4.97212 -5.61454 -6.01158 -6.14588 -6.01158"

In [38]:
flat = np.array(list(map(float, haha.split())))

In [40]:
flat.reshape(10, 10) - f[:10, :10]

array([[ 3.69979872e-08, -3.69979872e-08,  3.81858515e-07,  1.47707309e-07, -4.89285570e-08, -4.70434176e-07,  1.92567837e-07,  3.32929957e-07,  2.95414619e-07,  3.32929957e-07],
       [-3.69979872e-08,  3.69979872e-08, -3.81858515e-07, -1.47707309e-07,  4.89285570e-08,  4.70434176e-07, -1.92567837e-07, -3.32929957e-07, -2.95414619e-07, -3.32929957e-07],
       [ 3.81858515e-07, -3.81858515e-07, -1.92567837e-07, -4.80637267e-07,  1.37165542e-06, -3.67320510e-06, -5.50636181e-08,  2.17908759e-06,  1.03872547e-06,  2.17908759e-06],
       [ 1.47707309e-07, -1.47707309e-07, -4.80637267e-07, -3.67320510e-06, -4.20277093e-06,  1.84615763e-06, -2.30154968e-06,  1.31659181e-06,  2.65358979e-06,  1.31659181e-06],
       [-4.89285570e-08,  4.89285570e-08,  1.37165542e-06, -4.20277093e-06, -3.19870290e-06, -2.83111550e-06,  3.21781305e-06, -1.82704747e-06,  1.59445815e-06, -1.82704747e-06],
       [-4.70434176e-07,  4.70434176e-07, -3.67320510e-06,  1.84615763e-06, -2.83111550e-06, -1.82704747e

# Debug A, B, C, D

In [41]:
nx = 15 # 여기서는 cell의 개수
ny = 15
Lx = 1
Ly = 1
dx = 1/(nx)
dy = 1/ny
dxdx = dx**2


nx1 = 10
ny1 = 10

A = np.zeros(nx1-2)
B = np.zeros(nx1-2)
C = np.zeros(nx1-2)
D = np.zeros(nx1-2)

for i in range(nx1-2):
    A[i] = 1/dxdx
    B[i] = -2/dxdx

In [42]:
A

array([225., 225., 225., 225., 225., 225., 225., 225.])